[profile.default]
src = "src"
out = "out"
libs = ['lib']
solc = "0.8.21"
optimizer_runs = 1_000_000
bytecode_hash = "none"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
base = "${RPC_URL_BASE}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
base = { key = "${ETHERSCAN_BASE_KEY}" }
